// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzZLdLG1RysJoJeTpxwF9bIDI5Mjzt1Mc',
    appId: '1:923391695684:web:369c0b31c8c65ccd949511',
    messagingSenderId: '923391695684',
    projectId: 'todo-do-1ec9d',
    authDomain: 'todo-do-1ec9d.firebaseapp.com',
    storageBucket: 'todo-do-1ec9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfY7kf6U2xkZtwz3jXJsjdiliUE2aXs0Y',
    appId: '1:923391695684:android:5e4557410c20c9cf949511',
    messagingSenderId: '923391695684',
    projectId: 'todo-do-1ec9d',
    storageBucket: 'todo-do-1ec9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqshi6DJP0potRx6O1b6zi36IVYcJTz_0',
    appId: '1:923391695684:ios:6ceec8b948e45f5c949511',
    messagingSenderId: '923391695684',
    projectId: 'todo-do-1ec9d',
    storageBucket: 'todo-do-1ec9d.firebasestorage.app',
    iosBundleId: 'com.example.ntiRepo',
  );
}
